version: 2.1
jobs:
  test:
    docker:
      - image: python:2.7
    working_directory: ~/app
    steps:
      - checkout
      - run: pip install .[test]
      - run: DB=sqlite pytest
  release:
    docker:
      - image: python:2.7
    working_directory: ~/app
    steps:
      - checkout
      - run: |
          pip install twine
          pip install .
      - run: |
          python setup.py sdist
          twine upload --repository-url https://geru-pypi.geru.com.br/ dist/*
workflows:
  version: 2
  test-always:
    jobs:
      - test
  test-and-release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
